
name: Build & Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'environment'
        required: true
        type: choice
        options: [test, prod]

jobs:
  build:
    runs-on: ubuntu-latest
