name: Test 004
on: 
  workflow_dispatch:
    inputs:
      env:
        description: 'choose env'
        required: true
        type: choice
        options: [test, prod]
jobs:
  job1:
    runs-on: ubuntu-slim
    steps:
      - run: exit
